<?php 
return array(
        '' => '',

        'OAA'  => 'Academic Affairs, Office of',

        'ARC'  => 'Academic Research Computing',

        'BOAP'  => 'Accounts Payable',

        'SOGAJ'  => 'Administration of Justice (School of Government)',

        'ADM'  => 'Admissions Office',

        'AFM'  => 'Affirmative Action',

        'ALUM'  => 'Alumni Relations',
        'AAUP'  => 'American Association of University Professors',

        'ANTH'  => 'Anthropology',
        
        'LING' => 'Applied Linguistics',
        
        'ARA' => 'Aramark',

        'ARCH'  => 'Architecture',

        'ART'  => 'Art',
        
        'ASPSU' => 'Associated Students, PSU',
        
        'PHE' => 'Athletic Training Program',

        'ATH'  => 'Athletics',
        
        'AV' => 'Audio Visual Services',

		'AUXS' => 'Auxiliary Services',
		
		'ASA' => 'Auxiliary Services Accounting',

        'BIO'  => 'Biology',

        'BST'  => 'Black Studies',
        
        'BOX' => 'Box Office',

        'BUD'  => 'Budget Office',
        
//        'BAO' => 'Business Accounting',

//        'BA'  => 'Business Accelerator',

        'SBA'  => 'Business Administration, School of',
        
        'SBA-STUDENT SERVICES' => 'Business Administration,, Student Services',

        'BAO'  => 'Business Affairs',

		'KHSE' => 'Campus Ministry',
		
		'CPSO' => 'Campus Public Safety',

        'CREC'  => 'Campus Recreation',

        'REC'  => 'Campus Recreation Outdoor Program',

        'CARC'  => 'Career Center',
        
        'BOCA' => 'Cashiers',

        'CAE'  => 'Center for Academic Excellence',
        
        'CJS'  => 'Center for Japanese Studies',
        
        'COL' => 'Center for Online Learning',
        
        'CPS' => 'Center for Public Service',

        'CSE'  => 'Center for Science Education',
        
        'SUST' => 'Center for Sustainable Processes and Practices',
        
        'CST' => 'Center for Transportation Studies',

        'CUS'  => 'Center for Urban Studies',

        'CP'  => 'Challenge Program',
        
        'CHAN' => 'Chancellors Office',

        'CHEM'  => 'Chemistry',

        'CLS'  => 'Chicano-Latino Studies',
        
        'CFS' => 'Child and Family Services',

        'CCC'  => 'Child Care Center, ASPSU',

        'CDC'  => 'Child Development Center Helen Gordon',
        
        'CWP'  => 'Child Welfare Partnership',
        
        'CEE' => 'Civil and Environmental Engineering Department',
        
        'CHNW' => 'College Housing Northwest',

        'CLAS'  => 'College of Liberal Arts and Sciences',

        'SP'  => 'Communication',

        'CUSCES'  => 'Community Environment Services',

        'SCH'  => 'Community Health',

        'SCS'  => 'Computer Action Team',

        'CMPS'  => 'Computer Science',

        'CIS'  => 'Computing Infrastructure Services',

        'CR'  => 'Conflict Resolution',
        
        'CEED' => 'Continuing Education, School of Education',
        
        'CAPS' => 'Counseling & Psychological Services',
        
        'JUST' => 'Criminology and Criminal Justice, Division of',
        
        'DOS' => 'Dean of Students, Office of',

        'DEV'  => 'Development',

        'DEW'  => 'Dew Project',

        'DRC'  => 'Disability Resource Center',
        
        'ODI' => 'Diversity and Inclusion',

        'ECTC'  => 'Early Childhood Training Center',

        'ECON'  => 'Economics',

        'ED'  => 'School of Education',

        'EEPS'  => 'Educational Equity Programs',

        'EOP'  => 'Educational Opportunity Program',

        'ETS'  => 'Educational Talent Search',

        'ECE'  => 'Engineering & Applied Sciences',

        'CEE'  => 'Civil Engineering',

        'MCECS'  => 'Engineering Deans Office',

        'CECS'  => 'Electrical & Computer Engineering',

        'MME'  => 'Mechanical Engineering',

        'ETM'  => 'Engineering & Technology Management Program',

        'ENG'  => 'English',
        
        'EMSA' => 'Enrollment Management and Student Affairs',

        'ESR'  => 'Environmental Sciences & Resources',

        'XS'  => 'Extended Studies',

        'FAP'  => 'Facilities',

        'FADM'  => 'Finance and Administration',

        'FA'  => 'Finanical Aid',

        'FPA'  => 'Fine and Performing Arts',

        //'FLL'  => 'Foreign Language',

        'FOUND'  => 'Foundation',

        'GEOG'  => 'Geography',

        'GEOL'  => 'Geology',

        'GSE'   => 'Graduate Schoool Of Education',

        'SHAC'  => 'Health Services',

        'HST'  => 'History',

        'HON'  => 'Honors Program',

        'HRC'  => 'Human Resources',

        'IASC'  => 'Information and Academic Support Center',

        'IS'  => 'Information Systems',

        'IMS'  => 'Institute of Portland Metropolitan Studies',

        'IELP'  => 'Intensive English Language Program',

        'IS'  => 'International Studies',

        'LIB'  => 'Library',

        'OMC'  => 'Marketing and Communications',

        'MIM'  => 'Master of International Management',

        'MTH'  => 'Mathematics and Statistics',

        'MME'  => 'Mechanical and Materials Engineering',

        'MS'  => 'Military Science',

        'MCC'  => 'Multicultural Center',

        'MUS'  => 'Music',

        'NPC'  => 'National Policy & Consensus',

        'NAC'  => 'Native American Center',

        'NBS'  => 'Norris Beggs and Simpson',

        'OCCD'  => 'Oregon Cntr for Professional Development in Childhood Care & Ed',

        'OCEE'  => 'Oregon Council for Economic Education',

        'OGC'  => 'Office of the General Counsel',

		'OGS' => 'Office of Graduate Studies',

        'OIA'  => 'Office of International Affairs',

        'OIT' => 'Office of Information Technology',

        'OIRP'  => 'Office of Institutional Research & Planning',

        'OMB'  => 'Ombudsmans Office',

        'CSC'  => 'Oregon Community Service Commission',

        'SBAeMBA'  => 'Oregon Executive MBA Program',

        'OITPC'  => 'Oregon Institute of Technology Portland Center',

        'OSUPC'  => 'OSU Portland Center',

        'OSUWCE'  => 'OSU Washington County Extension',

	'PSRE' => 'Planning Sustainability and Real Estate',

        'PHL'  => 'Philosophy',

        'PHY'  => 'Physics',

        'PS'  => 'Political Science',

        'PRC'  => 'Population Research',

        'PO'  => 'Presidents Office',

        'PWB'  => 'Print & Web Group',

        'XSPDC'  => 'Professional Development Center',

        'PSY'  => 'Psychology',

        'PA'  => 'Public Administration',

        'PHE'  => 'Public Health Education',

        'BOPUR'  => 'Purchasing',

        'RRI'  => 'Regional Research Institute',

        'REG'  => 'Registration',
        
		'RSP' => 'Research and Strategic Partnerships',
		
        'SAT'  => 'Saturday Academy',

        'SOG'  => 'School of Government',

		'SSW'  => 'School of Social Work',

        'SSCBIO'  => 'Science Support Center',

        'SSCCSE'  => 'Science Support Shop (CSE & ESR)',

        'SOC'  => 'Sociology',

        'SPHR'  => 'Speech & Hearing Sciences',

        'SA'  => 'Student Affairs',

        'SALP'  => 'Student Activities & Leadership Programs',

        'LS'  => 'Student Legal and Mediation Services',

        'RRILAB'  => 'Survey Research Laboratory',

        'SYSC'  => 'Systems Science',

        'TELEEOU'  => 'Telecommunications EOU',

        'TA'  => 'Theater Arts',
        
        'TAPS' => 'Transportation and Parking Services',

        'QRC' => 'Queer Resource Center',

	    'UA'  => 'University Advancement',

        'UOPC'  => 'University of Oregon Portland Center',

        'UNST'  => 'University Studies',

        'UB'  => 'Upward Bound',

        'URBN'  => 'Urban and Public Affairs',

        'IOA'  => 'Urban and Public Affairs Institute On Aging',

        'UPA'  => 'Urban and Public Affairs LAB',

        'USP'  => 'Urban Studies & Planning',

        'USS'  => 'User Support Services',

        'VG'  => 'Vanguard',

        'WRC'  => 'Womens Resource Center',

        'WSC'  => 'Women Studies',

        'WLL'  => 'World Language & Literature',

        'YINP'  => 'Youth Intervention Network Project',
        
        
        
        
);
